# Generated by Django 6.0.3 on 2026-03-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_emergency', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_donors', models.IntegerField(default=13900)),
                ('units_month', models.IntegerField(default=10455)),
                ('emergency_requests', models.IntegerField(default=2)),
                ('hospitals', models.IntegerField(default=190)),
                ('total_units', models.IntegerField(default=2660)),
            ],
        ),
    ]
