# Generated by Django 6.0.3 on 2026-03-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('blood_group', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=255)),
                ('last_donated', models.DateField()),
                ('contact', models.CharField(max_length=20)),
                ('status', models.CharField(default='Available', max_length=20)),
            ],
        ),
    ]
