# Generated by Django 6.0.3 on 2026-03-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0002_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='reliability_score',
            field=models.FloatField(default=0.95),
        ),
        migrations.AlterField(
            model_name='donor',
            name='last_donated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(default='Eligible', max_length=20),
        ),
    ]
