# Generated by Django 6.0.3 on 2026-03-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0003_donor_reliability_score_alter_donor_last_donated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=255)),
                ('blood_group', models.CharField(max_length=5)),
                ('component', models.CharField(max_length=50)),
                ('available_units', models.IntegerField(default=0)),
                ('distance_km', models.FloatField()),
            ],
        ),
    ]
