# Generated by Django 6.0.3 on 2026-03-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0006_appointment_donationeligibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_id', models.CharField(max_length=20, unique=True)),
                ('blood_group', models.CharField(max_length=5)),
                ('units_needed', models.IntegerField()),
                ('urgency', models.CharField(choices=[('SOS', 'SOS'), ('High', 'High'), ('Normal', 'Normal')], default='Normal', max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Fulfilled', 'Fulfilled')], default='Pending', max_length=20)),
                ('matched_donors_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
